### Loading

In [ ]:
from pathlib import Path

import mgnify_methods.paper_modules as pm
from mgnify_methods.taxonomy import (
    pivot_taxonomic_data,
    aggregate_by_taxonomic_level,
)

from mgnify_methods.taxonomy import (
    remove_singletons_per_sample,
    prevalence_cutoff_abund,
)

from mgnify_methods.metacomp.transforms import (
    apply_transform_method,
)

In [2]:
root_dir = Path().resolve().parent
root_dir

WindowsPath('C:/Users/David Palecek/Documents/Python_projects/emobon/emobon-basic-models')

In [3]:
contig_path = root_dir / "configs" / "model_test.json"
CONFIG = pm.config_setup(root_dir, contig_path)

INFO | mgnify_methods.paper_modules | Directory ready: C:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\outputs\analysis_20260305_1208
INFO | mgnify_methods.paper_modules | Directory ready: C:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\analysis_cache
INFO | mgnify_methods.paper_modules | Configuration saved to: C:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\outputs\analysis_20260305_1208\analysis_config.json
INFO | mgnify_methods.paper_modules | Logger configured to write to C:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\outputs\analysis_20260305_1208\analysis.log

### Load cache if available

In [4]:
from utils.io import load_preprocessed_cache

In [5]:
try:
    preprocess_tables, emobon_meta = load_preprocessed_cache(root_dir, CONFIG)
except FileNotFoundError:
    print('needs manual processing')

Loaded preprocessing cache from: C:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\analysis_cache\model_testing

In [4]:
# loads both ssu and emobon metadata, 
abundance_emobon, emobon_meta = pm.load_emobon(root_dir, ret='ssu')
abundance_emobon.shape, emobon_meta.shape

c:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\.venv\Lib\site-packages\momics\metadata.py:263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata["replicate_info"] = (

((111320, 9), (181, 100))

In [5]:
abundance_emobon = pm.process_emobon_data(abundance_emobon, CONFIG)
abundance_emobon.shape

(7131, 181)

In [6]:
# turn abundance into taxonomy for cleaning lineaages
taxonomy_table = pm.clean_abundance_table(abundance_emobon, CONFIG)

tax_level = CONFIG['taxonomy']['analysis_level']
abundance_table = aggregate_by_taxonomic_level(
    taxonomy_table.df,
    level=tax_level,
    dropna=CONFIG['preprocessing']['dropna']
)
del taxonomy_table

INFO | mgnify_methods.tables.tables | Converting source: tax_mgnify_raw
WARNING | mgnify_methods.tables.tables | DataFrame is abundance without ncbi_tax_id data.
INFO | mgnify_methods.tables.tables | self.source before conversion to Taxonomy table: tax_mgnify_raw
INFO | mgnify_methods.tables.tables | Converting source: tax_processed
INFO | mgnify_methods.tables.sources.converters | Abundance dtype after conversion: uint16
INFO | mgnify_methods.tables.tables | Validating source: tax_processed
INFO | mgnify_methods.paper_modules | Taxonomy table ready: (111320, 9)

In [7]:
abundance_table = pivot_taxonomic_data(abundance_table)
type(abundance_table)

pandas.core.frame.DataFrame

## Processing of the raw abundance table
- remove singletons
- CLR

In [8]:
abundance_table_beta = remove_singletons_per_sample(abundance_table, skip_columns=0)

abundance_table_beta = prevalence_cutoff_abund(
        abundance_table, 
        percent=CONFIG['preprocessing']['prevalence_cutoff'],
        skip_columns=0
    )

preprocess_tables = {'emobon': abundance_table}

## Data transformation for beta diversity
if CONFIG['transform']['enabled']:
    transformed_tables = {}
    for sample_type, table_or_dict in preprocess_tables.items():
        if isinstance(table_or_dict, dict):
            transformed_tables[sample_type] = {
                tax_level: apply_transform_method(df, CONFIG)
                for tax_level, df in table_or_dict.items()
            }
        else:
            transformed_tables[sample_type] = apply_transform_method(table_or_dict, CONFIG)

    preprocess_tables = transformed_tables

INFO | mgnify_methods.metacomp.transforms |
=== Applying transform clr ===

Removed 10 singleton features. Shape reduced from (221, 181) → (211, 181)
Prevalence cutoff at 0.5% (max threshold 333.105): reduced from (221, 181) to (66, 181)

## Modelling

In [6]:
from emobon_models.modeling_config import modeling_config_from_analysis
from emobon_models.modeling_runner import run_group_loocv_with_mlflow

In [7]:
# filter metadata manually
emobon_meta_in = emobon_meta[CONFIG['modeling']['metadata_cols']]

In [8]:

modeling_config = modeling_config_from_analysis(CONFIG)
abundance_for_model = preprocess_tables["emobon"]

modeling_results = run_group_loocv_with_mlflow(
    metadata_df=emobon_meta_in,
    abundance_df=abundance_for_model,
    config=modeling_config,
)

modeling_results["summary_metrics"]

observatory ID observatory ID
BPNS        23
NRMCB       22
ROSKOGO     20
RFormosa    18
VB          16
AAOT        15
IUIEilat    12
PiEGetxo    12
EMT21       12
OSD74       11
MBAL4        8
ESC68N       6
OOB          3
HCMR-1       3
Name: count, dtype: int64
month name month name
Dec    54
Aug    49
Oct    46
Jun    18
Nov     8
Jul     6
Name: count, dtype: int64
tidal stage tidal stage
no_tide       62
low_tide      34
ebb_tide      33
flood_tide    27
high_tide     23
NA             2
Name: count, dtype: int64
longitude longitude
 14.250000    22
-7.969250     18
 7.317000     16
 2.808331     16
 12.508333    15
-3.968333     14
-8.798500     12
-3.014639     12
 34.916667    12
-8.666639     11
-4.217000      8
 2.808330      7
-3.866000      6
 17.125619     6
 3.135278      3
 25.278761     3
Name: count, dtype: int64
latitude latitude
51.433331    23
40.800139    22
37.005639    18
43.683000    16
45.314167    15
48.771667    14
42.201944    12
43.338583    12
29.500000    12
41.146528    11
50.250000     8
48.708333     6
68.925895     6
42.484167     3
35.346621     3
Name: count, dtype: int64
observatory regional location observatory regional location
North Atlantic Ocean    41
English Channel         28
North Sea               23
Tyrrhenian Sea          22
Villefranche Bay        16
Adriatic Sea            15
Bay of Biscay           12
Gulf of Eilat           12
Norwegian Sea            6
Gulf of Lion             3
Aegean Sea               3
Name: count, dtype: int64
environment (biome) environment (biome)
marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023]                                           68
marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023];mediterranean sea biome[ENVO_01000047]    48
marine biome [ENVO:00000447];marine benthic biome[ENVO_01000024]                                            30
marine biome [ENVO:00000447];estuarine biome [ENVO:01000020]                                                12
marine biome [ENVO:00000447]                                                                                12
marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023];estuarine biome [ENVO:01000020]           11
Name: count, dtype: int64
environmental package environmental package
water_column     151
soft_sediment     30
Name: count, dtype: int64
environment (material) environment (material)
seawater [ENVO:00002149]; coastal sea water [ENVO:00002150]; surface water [ENVO:00002042]    136
sediment [ENVO:00002007]                                                                       24
lagoon [ENVO_00000038];marine water body [ENVO:00001999]; surface water [ENVO:00002042]        12
lagoon [ENVO_00000038]; sediment [ENVO:00002007]                                                6
seawater [ENVO:00002149]; coastal sea water [ENVO:00002150]                                     3
Name: count, dtype: int64
sampling depth (m) sampling depth (m)
1.00     77
2.00     32
0.00     20
0.20     12
18.66    10
75.00     8
21.20     6
20.54     5
17.00     4
27.00     3
22.94     2
NaN       2
Name: count, dtype: int64

c:\Users\David Palecek\Documents\Python_projects\emobon\emobon-basic-models\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026/03/05 12:08:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/05 12:08:29 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/05 12:08:35 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

   mae_mean   mae_std  rmse_mean  rmse_std
0  3.598921  0.513574   7.158597  0.790428

In [7]:
emobon_meta.head()

,alkalinity (mEq/l),alkalinity method,ammonium (umol/l),ammonium method,bacterial production (ug/m3/d),bacterial production method,biomass (g/l),biomass method,chemical administration,chlorophyll (ug/l),...,water current (m3/s),water current method,year,month,month name,day,season,replicate info,study_tag,sample_type
source material ID,,,,,,,,,,,,,,,,,,,,,
EMOBON_OOB_So_1,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2021,6,Jun,8,Spring,OOB_soft_sediment_2021-06-08_NA,EMO-BON,prok
EMOBON_ESC68N_Wa_1,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,0.821,...,NaN,NaN,2021,8,Aug,30,Summer,ESC68N_water_column_2021-08-30_3-200,EMO-BON,prok
EMOBON_ESC68N_Wa_2,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,0.821,...,NaN,NaN,2021,8,Aug,30,Summer,ESC68N_water_column_2021-08-30_3-200,EMO-BON,prok
EMOBON_ESC68N_Wa_3,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,0.821,...,NaN,NaN,2021,8,Aug,30,Summer,ESC68N_water_column_2021-08-30_0.2-3,EMO-BON,prok
EMOBON_ESC68N_Wa_4,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,0.821,...,NaN,NaN,2021,8,Aug,30,Summer,ESC68N_water_column_2021-08-30_0.2-3,EMO-BON,prok

In [9]:
abundance_for_model.head()

source material ID,EMOBON_AAOT_Wa_1,EMOBON_AAOT_Wa_2,EMOBON_AAOT_Wa_22,EMOBON_AAOT_Wa_26,EMOBON_AAOT_Wa_27,EMOBON_AAOT_Wa_41,EMOBON_AAOT_Wa_42,EMOBON_AAOT_Wa_46,EMOBON_AAOT_Wa_47,EMOBON_AAOT_Wa_6,...,EMOBON_VB_Wa_4,EMOBON_VB_Wa_41,EMOBON_VB_Wa_42,EMOBON_VB_Wa_43,EMOBON_VB_Wa_44,EMOBON_VB_Wa_5,EMOBON_VB_Wa_93,EMOBON_VB_Wa_94,EMOBON_VB_Wa_96,EMOBON_VB_Wa_97
taxonomic_concat,,,,,,,,,,,,,,,,,,,,,
sk__Archaea;k__;p__;c__;o__;f__;g__;s__,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,...,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975,-2.537975
sk__Archaea;k__unclassified_Crenarchaeota;p__Crenarchaeota;c__;o__;f__;g__;s__,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,...,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570,-0.972570
sk__Archaea;k__unclassified_Euryarchaeota;p__Euryarchaeota;c__;o__;f__;g__;s__,-12.369128,15.251843,-12.369128,-12.369128,-12.369128,-12.369128,12.543792,15.375222,14.972877,-12.369128,...,-12.369128,-12.369128,-12.369128,-12.369128,-12.369128,-12.369128,-12.369128,-12.369128,-12.369128,-12.369128
sk__Archaea;k__unclassified_Thaumarchaeota;p__Thaumarchaeota;c__;o__;f__;g__;s__,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,...,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912,-7.635912
sk__Bacteria;k__;p__;c__;o__;f__;g__;s__,0.760431,1.110797,1.184824,0.421568,-0.091122,0.367625,-0.241858,-0.094860,-0.658228,0.691211,...,0.264620,0.269835,0.633249,0.903373,0.528491,0.510254,-0.252763,-0.061708,1.178555,0.645828

In [11]:
[k for k in abundance_for_model.index if 'p__;' in k]

['sk__Archaea;k__;p__;c__;o__;f__;g__;s__',
 'sk__Bacteria;k__;p__;c__;o__;f__;g__;s__',
 'sk__Eukaryota;k__;p__;c__;o__;f__;g__;s__']

In [12]:
filtered = abundance_for_model[~abundance_for_model.index.str.contains('p__;')]

In [13]:
[k for k in filtered.index if 'p__;' in k]

[]

In [14]:
abundance_for_model.shape, filtered.shape

((66, 181), (63, 181))

In [12]:
emobon_meta.columns

Index(['alkalinity (mEq/l)', 'alkalinity method', 'ammonium (umol/l)',
       'ammonium method', 'bacterial production (ug/m3/d)',
       'bacterial production method', 'biomass (g/l)', 'biomass method',
       'chemical administration', 'chlorophyll (ug/l)', 'chlorophyll method',
       'collection_date', 'conductivity (mS/cm)', 'conductivity method',
       'density (g/m3)', 'density method', 'sampling depth (m)',
       'dissolved carbon dioxide (umol/l)', 'dissolved carbon dioxide method',
       'dissolved inorganic carbon (ug/l)',
       'dissolved inorganic carbon method',
       'dissolved organic carbon (umol/l)', 'dissolved organic carbon method',
       'dissolved organic nitrogen (ug/l)',
       'dissolved organic nitrogen method', 'dissolved oxygen (mmol/kg)',
       'dissolved oxygen method', 'visible waveband radiance (uE/m2/s)',
       'downward PAR method', 'environment (biome)', 'environment (feature)',
       'environment (material)', 'environmental package', 'country',
       'investigation type', 'latitude', 'observatory location ocean or sea',
       'observatory local location', 'observatory regional location',
       'longitude', 'n-alkanes', 'n-alkanes method', 'nitrate (umol/l)',
       'nitrate method', 'nitrite (umol/l)', 'nitrite method',
       'observatory ID', 'organism count', 'organism count method',
       'organization', 'organization country',
       'particulate organic carbon (ug/l)',
       'particulate organic carbon method',
       'particulate organic nitrogen (ug/l)',
       'particulate organic nitrogen method', 'petroleum hydrocarbon (umol/l)',
       'petroleum hydrocarbon method', 'pH', 'pH method',
       'phaeopigments (ug/l)', 'phaeopigments method', 'phosphate (umol/l)',
       'phosphate method', 'pigments (ug/l)', 'pigments method',
       'pressure (atm)', 'pressure method', 'primary production (mg/m3/d)',
       'primary production method', 'project name', 'replicate number',
       'sample collection device or method', 'sea subsurface salinity (PSU)',
       'sea subsurface salinity method', 'sea subsurface temperature (C)',
       'sea subsurface temperature method', 'sea surface salinity (PSU)',
       'sea surface salinity method', 'sea surface temperature (C)',
       'sea surface temperature method', 'silicate (umol/l)',
       'silicate method', 'sulfate (umol/l)', 'sulfate method',
       'sulfide (umol/l)', 'sulfide method', 'tidal stage', 'total depth (m)',
       'turbidity (FNU)', 'turbidity method', 'water current (m3/s)',
       'water current method', 'year', 'month', 'month name', 'day', 'season',
       'replicate info', 'study_tag', 'sample_type'],
      dtype='object')

In [13]:
emobon_meta['observatory ID'].value_counts()

observatory ID
BPNS        23
NRMCB       22
ROSKOGO     20
RFormosa    18
VB          16
AAOT        15
IUIEilat    12
PiEGetxo    12
EMT21       12
OSD74       11
MBAL4        8
ESC68N       6
OOB          3
HCMR-1       3
Name: count, dtype: int64

In [10]:
for column in emobon_meta.columns:
    print(column, emobon_meta[column].value_counts(dropna=False))

alkalinity (mEq/l) alkalinity (mEq/l)
NaN    181
Name: count, dtype: int64
alkalinity method alkalinity method
NaN    181
Name: count, dtype: int64
ammonium (umol/l) ammonium (umol/l)
NaN       131
0.1300      4
0.5300      4
0.4100      4
0.3600      4
0.2400      4
0.0044      4
0.8600      4
0.6600      4
5.8800      4
0.1400      4
2.2500      4
0.5400      3
1.7300      2
4.5700      1
Name: count, dtype: int64
ammonium method ammonium method
NA                                                                                                                                                                                                                         152
segmented continuous-flow autoanalyzer                                                                                                                                                                                      14
Spectrophotometry                                                                                                                                                                                                           11
from https://www.westernchannelobservatory.org.uk/, 5-channel Bran and Luebbe segmented flow system following MANTOURA, R.F.C, and WOODWARD, E.M.S., (1983). Estuarine, Coastal and Shelf Science, (1983), 17, 219-224.      4
Name: count, dtype: int64
bacterial production (ug/m3/d) bacterial production (ug/m3/d)
NaN    181
Name: count, dtype: int64
bacterial production method bacterial production method
NaN    181
Name: count, dtype: int64
biomass (g/l) biomass (g/l)
NaN    181
Name: count, dtype: int64
biomass method biomass method
NaN    181
Name: count, dtype: int64
chemical administration chemical administration
NaN    181
Name: count, dtype: int64
chlorophyll (ug/l) chlorophyll (ug/l)
NaN          78
21.690000     6
8.868800      6
3.981320      6
2.290000      4
0.549000      4
1.710000      4
0.266000      4
0.094167      4
1.130000      4
0.821000      4
2.160000      4
0.320000      4
0.248070      4
0.502835      4
0.227000      4
0.230000      4
0.270819      4
0.214000      4
1.720000      4
0.390000      4
0.280000      4
2.620000      3
0.080000      3
0.236000      3
1.660000      2
0.518000      2
Name: count, dtype: int64
chlorophyll method chlorophyll method
NA                                                                                            62
Fluorometer 10-AU                                                                             18
HPLC                                                                                          16
filtration on 0.2 um FG filters. extraction in acetone overnight. fluorimetric measurement    15
spectrofluorometry                                                                            14
HPLC (Alliance HPLC System) following the method described by Zapata et al. 2000              12
Chlorophyll extraction                                                                        12
Spectrophotometry                                                                             11
Trilogy fluorometer - Module: CHL-A NA model # 7200-046                                        8
photometric measurement                                                                        6
TD-700 Laboratory Fluorometer                                                                  3
Trilogy fluorometer - Module: CHL-A NA model # 7200-044                                        1
Trilogy fluorometer - Module: CHL-A NA model # 7200-045                                        1
Trilogy fluorometer - Module: CHL-A NA model # 7200-042                                        1
Trilogy fluorometer - Module: CHL-A NA model # 7200-043                                        1
Name: count, dtype: int64
collection_date collection_date
2021-10-28    10
2021-08-25     9
2021-08-31     9
2021-06-21     8
2021-12-16     8
2021-10-18     8
2021-08-05     6
2021-12-23     6
2021-12-20     6
2021-10-22     6
2021-12-21     6
2021-10-26     6
2021-08-30     4
2021-07-01     4
2021-08-02     4
2021-08-23     4
2021-10-27     4
2021-12-22     4
2021-11-03     4
2021-08-29     4
2021-10-20     4
2021-12-19     4
2021-08-24     4
2021-06-22     4
2021-10-15     4
2021-12-14     4
2021-12-18     4
2021-12-13     4
2021-12-17     4
2021-10-14     4
2021-06-28     3
2021-08-09     3
2021-11-04     2
2021-06-18     2
2021-08-26     2
2021-07-26     2
2021-11-19     2
2022-12-22     2
2021-12-09     2
2021-06-08     1
Name: count, dtype: int64
conductivity (mS/cm) conductivity (mS/cm)
NaN            116
46.0700          4
40702.4000       4
46.4582          4
44.6300          4
21.8465          4
47.8993          4
47.8943          4
40.6864          4
44.8400          4
39.4740          4
40.3690          4
38.9700          4
31.6300          4
444968.3080      3
9642.9000        3
42401.0000       2
56.5917          2
44968.3080       1
42401.0040       1
42401.0050       1
Name: count, dtype: int64
conductivity method conductivity method
NA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             108
CTD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             12
SBE_37ODO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       12
EXO2 multiparameter sonde                                                                                                                                                                                                                                                                                                                                                                                                                                                                       12
CTD SBE911plusV2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                12
in situ multiparametric probe                                                                                                                                                                                                                                                                                                                                                                                                                                                                   11
Valeport MIDAS 606 CTD (with a passive flow induction cell, Platinum Resistance Thermometer and a Temperature Compensated Piezo-Resistive Sensor ) with titanium housing. Full equipment specification is described by Valeport Ltd., 2006. Data were extracted and processed using Valeport DataLogX2 software (version1.0.4.1270). Manufacturer calibrations were applied to the direct measurements and parameters were derived using the in-built functions in the software Datalog X2.      8
CTD broke and conductivity could not be measured                                                                                                                                                                                                                                                                                                                                                                                                                                                 4
CTD SBE 19plusV2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2
Name: count, dtype: int64
density (g/m3) density (g/m3)
NaN          159
25.0316        4
1025.6200      4
27.8126        4
1026.4980      4
27.8143        4
25.2822        2
Name: count, dtype: int64
density method density method
NA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             147
CTD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             12
CTD SBE911plusV2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                12
Valeport MIDAS 606 CTD (with a passive flow induction cell, Platinum Resistance Thermometer and a Temperature Compensated Piezo-Resistive Sensor ) with titanium housing. Full equipment specification is described by Valeport Ltd., 2006. Data were extracted and processed using Valeport DataLogX2 software (version1.0.4.1270). Manufacturer calibrations were applied to the direct measurements and parameters were derived using the in-built functions in the software Datalog X2.      8
CTD SBE 19plusV2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2
Name: count, dtype: int64
sampling depth (m) sampling depth (m)
1.00     77
2.00     32
0.00     20
0.20     12
18.66    10
75.00     8
21.20     6
20.54     5
17.00     4
27.00     3
22.94     2
NaN       2
Name: count, dtype: int64
dissolved carbon dioxide (umol/l) dissolved carbon dioxide (umol/l)
NaN    181
Name: count, dtype: int64
dissolved carbon dioxide method dissolved carbon dioxide method
NaN    181
Name: count, dtype: int64
dissolved inorganic carbon (ug/l) dissolved inorganic carbon (ug/l)
NaN    181
Name: count, dtype: int64
dissolved inorganic carbon method dissolved inorganic carbon method
NaN    181
Name: count, dtype: int64
dissolved organic carbon (umol/l) dissolved organic carbon (umol/l)
NaN    181
Name: count, dtype: int64
dissolved organic carbon method dissolved organic carbon method
NaN    181
Name: count, dtype: int64
dissolved organic nitrogen (ug/l) dissolved organic nitrogen (ug/l)
NaN    181
Name: count, dtype: int64
dissolved organic nitrogen method dissolved organic nitrogen method
NaN    181
Name: count, dtype: int64
dissolved oxygen (mmol/kg) dissolved oxygen (mmol/kg)
NaN         113
256.0000      6
272.0000      6
219.0000      6
7.4900        4
7.1900        4
7.4390        4
8.1400        4
237.1410      4
4.6070        4
4.5980        4
4.9395        4
4.9290        4
5.9200        4
4.7913        2
5.0000        2
4.7075        2
5.5224        2
4.9882        2
Name: count, dtype: int64
dissolved oxygen method dissolved oxygen method
NA                                                                                                  91
YSI ProSolo Digital                                                                                 18
CTD                                                                                                 17
SBE 43                                                                                              14
SBE_37ODO                                                                                           12
in situ multiparametric probe                                                                       11
SBE43                                                                                                8
CTD broke and dissolved oxygen could not be measured                                                 4
from https://www.westernchannelobservatory.org.uk/ collected using oxygen optode,  data from 2 m     4
no CTD taken                                                                                         2
Name: count, dtype: int64
visible waveband radiance (uE/m2/s) visible waveband radiance (uE/m2/s)
NaN    181
Name: count, dtype: int64
downward PAR method downward PAR method
NaN    181
Name: count, dtype: int64
environment (biome) environment (biome)
marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023]                                           68
marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023];mediterranean sea biome[ENVO_01000047]    48
marine biome [ENVO:00000447];marine benthic biome[ENVO_01000024]                                            30
marine biome [ENVO:00000447];estuarine biome [ENVO:01000020]                                                12
marine biome [ENVO:00000447]                                                                                12
marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023];estuarine biome [ENVO:01000020]           11
Name: count, dtype: int64
environment (feature) environment (feature)
marine pelagic feature [ENVO:01000044];marine water body [ENVO:00001999];costal water body [ENVO:02000049]                          121
shallow_marine_sediment_[ENVO:03000034]                                                                                              24
lagoon [ENVO_00000038];marine water body [ENVO:00001999]                                                                             12
marine pelagic feature [ENVO:01000044];marine water body [ENVO:00001999];harbor[ENVO:00000463]                                       12
marine pelagic feature [ENVO:01000044];marine water body [ENVO:00001999];costal water body [ENVO:02000049];fjord [ENVO_00000039]      6
lagoon [ENVO_00000038];shallow_marine_sediment [ENVO:03000034]                                                                        6
Name: count, dtype: int64
environment (material) environment (material)
seawater [ENVO:00002149]; coastal sea water [ENVO:00002150]; surface water [ENVO:00002042]    136
sediment [ENVO:00002007]                                                                       24
lagoon [ENVO_00000038];marine water body [ENVO:00001999]; surface water [ENVO:00002042]        12
lagoon [ENVO_00000038]; sediment [ENVO:00002007]                                                6
seawater [ENVO:00002149]; coastal sea water [ENVO:00002150]                                     3
Name: count, dtype: int64
environmental package environmental package
water_column     151
soft_sediment     30
Name: count, dtype: int64
country country
France            39
Italy             37
Portugal          29
Spain             24
Belgium           23
Israel            12
United Kingdom     8
Norway             6
Greece             3
Name: count, dtype: int64
investigation type investigation type
metagenome    181
Name: count, dtype: int64
latitude latitude
51.433331    23
40.800139    22
37.005639    18
43.683000    16
45.314167    15
48.771667    14
42.201944    12
43.338583    12
29.500000    12
41.146528    11
50.250000     8
48.708333     6
68.925895     6
42.484167     3
35.346621     3
Name: count, dtype: int64
observatory location ocean or sea observatory location ocean or sea
North Atlantic Ocean                 63
Mediterranean Sea - Western Basin    41
Atlantic Ocean                       41
Mediterranean Sea - Eastern Basin    18
Indian Ocean                         12
Arctic Ocean                          6
Name: count, dtype: int64
observatory local location observatory local location
Belgian part of the North Sea          23
Naples Gulf                            22
French part of the English Channel     20
Ria Formosa                            18
Villefranche Bay - Point B             16
Gulf of Venice                         15
Gulf of Eilat                          12
Abra de Bilbao                         12
Vigo Seamount                          12
Porto Valley                           11
Western Channel                         8
Norwegian part of the Norwegian Sea     6
Bay of Banyuls-sur-Mer                  3
Crete Sea                               3
Name: count, dtype: int64
observatory regional location observatory regional location
North Atlantic Ocean    41
English Channel         28
North Sea               23
Tyrrhenian Sea          22
Villefranche Bay        16
Adriatic Sea            15
Bay of Biscay           12
Gulf of Eilat           12
Norwegian Sea            6
Gulf of Lion             3
Aegean Sea               3
Name: count, dtype: int64
longitude longitude
 14.250000    22
-7.969250     18
 7.317000     16
 2.808331     16
 12.508333    15
-3.968333     14
-8.798500     12
-3.014639     12
 34.916667    12
-8.666639     11
-4.217000      8
 2.808330      7
-3.866000      6
 17.125619     6
 3.135278      3
 25.278761     3
Name: count, dtype: int64
n-alkanes n-alkanes
NaN    181
Name: count, dtype: int64
n-alkanes method n-alkanes method
NaN    181
Name: count, dtype: int64
nitrate (umol/l) nitrate (umol/l)
NaN       113
3.030       4
1.750       4
0.230       4
1.080       4
4.370       4
0.010       4
14.430      4
1.210       4
6.995       4
0.240       4
0.030       4
1.070       4
45.310      4
4.990       4
34.830      4
32.250      3
0.080       3
0.640       2
Name: count, dtype: int64
nitrate method nitrate method